/*************************************************************************//**
 *
 *    @file           gpio_debug.c
 *    @date           05.05.2026
 *    @version        0.2.0
 *
 *    @author         Samuele Masciadri
 *
 ******************************************************************************
 *
 *    @brief          This file implements the GPIO debug module for
 *                    LED_RED (PB7), LED_YELLOW (PB6) and LED_GREEN (PB5)
 *                    in the "Piattaforma didattica ARM STM32F042K6Tx".
 *
 *                    Provides direct register access macros (no HAL) to
 *                    support GPIO debugging techniques.
 *
 ******************************************************************************/

/* Private includes ----------------------------------------------------------*/
#include "gpio_debug.h"

/* Private defines -----------------------------------------------------------*/

/* Private data types --------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/

/* Exported functions --------------------------------------------------------*/

/******************************************************************************/
/*!
 *    @brief  Initialises the debug GPIO state.
 *            Must be called after MX_GPIO_Init() generated by CubeMX.
 *            Sets all debug LEDs to the OFF state.
 *
 *    @param  None
 *    @retval None
 */
void gpio_debug_init(void)
{
    ALL_LEDS_OFF();
}

/******************************************************************************/
/*!
 *    @brief  Example: Technique A -- verifies that a critical code section
 *            is reached by generating a pulse on LED_RED (PB7).
 *
 *    @param  None
 *    @retval None
 */
void gpio_debug_section_check(void)
{
    LED_RED_ON();

    /* --- code section under analysis --- */

    LED_RED_OFF();
}

/******************************************************************************/
/*!
 *    @brief  Example: Technique B -- tracks execution time by toggling
 *            LED_GREEN (PB5) at entry and exit.
 *
 *    @param  None
 *    @retval None
 */
void gpio_debug_function_trace(void)
{
    LED_GREEN_TOGGLE();

    /* --- code under analysis --- */

    LED_GREEN_TOGGLE();
}

/* Private functions ---------------------------------------------------------*/

/****** END OF FILE ***********************************************************/
